title: Mehdi Seyfi
description: "Hi, I’m Mehdi, and I use this blog to document my learning journey. I am a Research scientist at Meta 🧠 | Exploring computer vision, computational photography, and Gen-AI 🚀"
show_downloads: False
google_analytics:
theme: jekyll-theme-architect
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
