title: Mehdi Seyfi
description: "Hi, I’m Mehdi, and I use this blog to document my learning journey. I am a Research scientist at Meta 🧠 | Exploring computer vision, computational photography, and Gen-AI 🚀"
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
